on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: venkatamutyala/hello-world-javascript-action@v1.4
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Create test.yaml file
        run: |
          echo "Hello, world!" > test.yaml
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          git checkout main
          echo "updating image tag in values file"
          git add . && git commit -m "update image tag"
          git push
 