on: [push, workflow_dispatch]


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: venkatamutyala/hello-world-javascript-action@v1.4
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Create test.yaml file
        run: echo "Hello, world!" > test.yaml

      - name: Commit and push changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add test.yaml file'
          commit_options: '--no-verify'
          file_pattern: 'test.yaml'
          branches: 'main'