on: 
  workflow_dispatch:
    inputs:
      manifest_to_update:
      tag:
      

concurrency:
  group: 'tag-updater'
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: 
        run: echo 'Updating ${{ inputs.manifest_to_update }} with tag ${{ inputs.tag }}'

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Update Container Image Tag
        run: |
          sed -i -e '/^- name: image.tag/{n;s/value:.*/value: ${{ inputs.tag }}/;}' ${{ inputs.manifest_to_update }}
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          git checkout main
          echo "updating image tag in values file"
          git add . && git commit -m "update image tag"
          git push
 